fkling/astexplorer

package.json
Flow's `import typeof ...` syntax was previously unsupported in `14001.1.0-dev-harmony-fb`. `15001.1.0-dev-harmony-fb` supports it.
Tested with a few random files, nothing seemed obviously broken.
=> update esprima-fb to 15001.1.0-dev-harmony-fb

src/TransformOutput.js
Sometimes you get super cryptic error messages in the transform output panel, like `false !== true`, but if you break on errors the actual error object has good better info. This change logs these errors to the console so you can get better stack traces + jump to where the error is happening to investigate. The `console.clear` removes them when the change starts working so it doesn't spam to much.
=> `console.error` any transform errors

package.json, src/TransformOutput.js, src/transformers/babel.js, src/transformers/jscodeshift.js
This guards against infinite loops using the halting-problem module.
It catches simple cases like the following statically:
```js
export default function ({Plugin, types: t}) {
return new Plugin('ast-transform', {
visitor: {
Identifier(node) {
var n = 100;
while (true) n++;
return t.identifier(node.name.split('').reverse().join(''));
}
}
});
}
```
results in
> while statement on line 6 has a constant test.  Either it is always `false` (making the statement redundant) or it is an infinite loop.
It can catch more subtle infinite loops like the following by checking for a timeout (of say 5 seconds) in all loops.  In this case it will just give you a message of "Infinite loop detected on line 6"
```js
export default function ({Plugin, types: t}) {
return new Plugin('ast-transform', {
visitor: …
```
=> Guard against infinite loops

src/getFocusPath.js
Set uses `has` not `contains` (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has).
It looks to be related to change: https://github.com/fkling/esprima_ast_explorer/commit/4ebc1fb119452479d8623c0085cefb9847e2ac0f#diff-88541fdf6f0855d0c9f2f9c3a51c48c2R35.
=> Fix method Set uses for membership

src/Editor.js, src/PasteDropTarget.js, src/parsers/css/index.js, src/parsers/html/index.js, src/parsers/js/index.js
This will allow category manifests to define their mime types without touching PasteDropTarget and import their CodeMirror modes without touching Editor.
=> Delegate more category-related responsibilities to categories.

package.json, src/Editor.js, src/TransformOutput.js, src/parsers/js/transformers/babel/index.js, src/parsers/js/transformers/babel6/index.js
This enables ability to map AST to resulting code, so that chunks in both editors are now highlighted.
All that transformer needs to do is return pair `{ code, map }` instead of just `code` if it supports source maps.
Currently works for:
* `babel`
* `babelv6`
* `postcss`
=> Add AST -> transformed code highlighting with source maps.

src/parsers/js/transformers/jscodeshift/index.js
Added a hack to prevent errors on jscodeshift.registerMethods when editing, while still throwing on duplicates within same run.
Fixes #22.
=> Fix jscodeshift.registerMethods duplicates error across different runs.

src/components/ast/Element.js, src/components/visualization/Tree.js, src/parsers/css/cssom.js, src/parsers/css/postcss.js, src/parsers/css/rework.js, src/parsers/graphql/graphql-js.js, src/parsers/html/htmlparser2.js, src/parsers/html/parse5.js, src/parsers/js/acorn.js, src/parsers/js/babel-eslint.js, src/parsers/js/babylon.js, src/parsers/js/babylon6.js, src/parsers/js/espree.js, src/parsers/js/esprima.js, src/parsers/js/recast.js, src/parsers/js/shift.js, src/parsers/js/traceur.js, src/parsers/js/typescript.js, src/parsers/js/uglify.js, src/parsers/utils/defaultParserInterface.js
Added the ability to hide the node's location data in order to remove clutter when interrogating the structure and data of the node.
Location property names are configurable per parser.
=> Add ability to hide location data

README.md, package.json, src/parsers/js/flow.js
`flow-parser` is a compiled-to-JS version of the OCaml Flow parser. It's mildly out of date right now, but I'll follow up with a version bump once we ship Flow 0.21 in the next few weeks.
Tested this by building locally, loading up, trying out the new parser. Settings tab is grayed out for now -- parsing works.
=> Add flow-parser

src/parsers/js/babylon.js
The `changeOption` handler was attempting to read from `target.vaue` instead of `target.value`. Previously, changing `sourceType` from "module" (the default) to "script" would cause the parser to warn about module-specific code, but reopening settings would show that `sourceType` was still "module".
=> Fix bug changing Babylon sourceType

src/parsers/js/espree.js
Previously, the Espree docs had the option as `comments`, though the correct name is `comment`. The Espree documentation was corrected in eslint/espree#248.
=> Fix Espree comment option

src/parsers/js/espree.js
Previously, `ecmaVersion` was being set as a string, but Espree expects a number. This change ensures that `ecmaVersion` is always set as a number.
=> Fix Espree ecmaVersion setting

npm-shrinkwrap.json, package.json, src/parsers/js/acorn.js, src/parsers/js/espree.js
Acorn 3.0.0 added support for `ecmaVersion: 7` and the exponentiation operator. Upgrading to 3.0.4 fixes a bug with the exponentiation operator.
Espree 3.1.0 adds support for `ecmaVersion: 7` and the exponentiation operator.
--
I tried doing this without altering `npm-shrinkwrap.json`, but that didn't work. If you'd like me to `git checkout master -- npm-shrinkwrap.json` to remove it from this PR so you can handle those changes yourself, I'm happy to do that.
=> Upgrade Acorn and Espree for ES7 support

npm-shrinkwrap.json
This is in the same spirit as 790d032a8a428b4aae7f07e3d7c5c4ce08b11492, but fixes the case where shrinkwrap is used when installing.
=> npm-shrinkwrap: use regular version of UglifyJS

src/CategoryButton.js, src/parsers/index.js, src/parsers/webidl/index.js, src/parsers/webidl/utils/mode.js
Before the CodeMirror IDL mode was used, which was not for Interface Definition Language but rather for the unrelated Interactive Data Language.
The Web IDL mode for CodeMirror, included in this PR, is adapted from the mode submitted to CM as codemirror/CodeMirror#3933.
=> Add proper Web IDL highlighting

npm-shrinkwrap.json, package.json, src/parsers/js/transformers/babel6/index.js
Fixes syntax errors in babel6 caused by #112. Doesn't fix #120, but fixes the reason I created #120.
=> Add babel6 syntax preset.

src/TransformOutput.js
It allow Transformer#transform to work as async.
I think that it is needed to implemenet async tranform like [stylelint](http://stylelint.io/ "stylelint") #118 and [textlint](https://textlint.github.io/ "textlint").
These tools has only async linting(transform) function.
- https://github.com/textlint/textlint/blob/master/docs/use-as-modules.md#core `textlint.lintText()` return `Promise<TextLintResult>`
- http://stylelint.io/user-guide/node-api/ `stylelint.lint()` reutn `Promise`.
P.S. I work on adding [textlint](https://textlint.github.io/ "textlint") to astexplorer which will be fork version. https://github.com/azu/astexplorer/pull/1
Async transform was needed to support textlint's transform.
=> Allow `transform` of Transformers to return promise

src/parsers/js/typescript.js
The `parent` property causes many AST elements to highlight rather than the selected element. Since the information is already visualized as a tree, the `parent` property provides no additional information.
=> Remove `parent` property from TypeScript AST

npm-shrinkwrap.json, package.json, src/parsers/css/postcss.js
I've added `postcss-less` PostCSS parser from https://github.com/webschik/postcss-less. Everything seems straightforward to add a new plugin in PostCSS and I've tested the output of the tree but I might have missed a few things or two. Please let me know if so.
=> Add postcss-less as one of the PostCSS parsers

.gitignore
Is it just me or should we be ignoring node_modules in `packages/`? for example https://github.com/fkling/astexplorer/tree/master/packages/babel6
=> gitignore packages/*/node_modules

package.json
Updates:
* Support for defaults in type parameter declarations (i.e. `type T<A=number> = ...`)
* Support for `declare module.exports`
* Support for exponentiation operator (`**`)
* Fixed parsing of `/x/* 5 */y/` - that's no comment!
* Fixed parsing of newlines or comments at the end of a template literal.
* Support for `declare export` within `declare module {}` bodies
=> Bump flow-parser to v0.28

package.json, src/parsers/js/esformatter.js
The AST used by [esformatter](https://github.com/millermedeiros/esformatter) is very similar to `babel-eslint`, but we also have a linked list of tokens (which can be accessed through the `startToken`/`endToken` props); Nodes that are inside Arrays, also have `next` and `prev` properties (see [rocambole](https://github.com/millermedeiros/rocambole) for more details). Given these differences, I believe it's worth the addition.
This will make it easier for contributors to [write plugins](https://github.com/millermedeiros/esformatter/wiki/Plugins) and fix bugs.
=> add esformatter to parsers

package.json
Flow v0.32.0 introduces new syntax, so a new version of `flow-parser` is out and it would be useful here.
=> flow-parser: Update to v0.32.0

webpack.config.js
The exception `Path must be a string` comes from `html-webpack-plugin`, v1.7.0, [this line](https://github.com/ampedandwired/html-webpack-plugin/blob/v1.7.0/index.js#L205).
Passing `filename` explicitly fixes it.
Closes #137
=> build: fix for Node 6

src/parsers/js/transformers/jscodeshift/codeExample.txt
A few changes to hopefully make it more beginner friendly
- Rename the variable `p` to `path` to make it more explicit
- Add `{}` inside of the arrow function in order to be able to add `console.log` more easily
- Use `forEach` instead of directly `replaceWith` as it's extremely likely that the codemod the person is going to write is not going to be as straightforward as just replacing a node with another one.
- Remove the default template stuff. I looked for [cpojer/js-codemods](https://github.com/cpojer/js-codemod) & [reactjs/react-codemod](https://github.com/reactjs/react-codemod) and there isn't a single use of those. We should document how they work and get people to use it, but I don't think it is useful to keep them by default.
- Remove the last `;` as it triggers a lint error on …
=> Update jscodeshift default

package.json, src/TransformOutput.js, src/parsers/js/transformers/babel6/index.js, yarn.lock
@fkling one thing about the yarn.lock change is that the urls changed to `https://registry.yarnpkg.com/acorn-to-esprima` instead of `https://registry.npmjs.org/acorn-to-esprima
Not sure if we want this by default (seems fine?)
Babel can now take in `recast@0.11.16` (`ast-types@0.9.1`) as a parser/generator
```js
import 'recast' from 'recast';
babel.transform(code, {
parserOpts: {
parser: recast.parse,
},
generatorOpts: {
generator: recast.print,
}
}
```
```js
// .babelrc
{
"parserOpts": {
"parser": "recast"
},
"generatorOpts": {
"generator": "recast",
}
}
```
a local test with object shorthand/method transform
=> Use recast in babel transform

src/parsers/js/transformers/babel6/codeExample.txt
and maybe we should actually use babel.types somehow?
=> add a name, remove parameter destructuring [skip ci]

src/parsers/css/cssom.js, src/parsers/css/rework.js, src/parsers/html/htmlparser2.js, src/parsers/js/flow.js, src/parsers/js/transformers/jscodeshift/index.js, src/parsers/webidl/webidl2.js
I saw that a few of the links were missing for various parsers/transformers.  I went ahead and added fallbacks for the missing homepages.  A better fix would be to submit PR's to the upstream repos so each package.json has a `homepage` value, but this is an okay stopgap IMO.
Here are the packages and the homepages I included:
https://www.npmjs.com/package/cssom - https://github.com/NV/CSSOM
https://www.npmjs.com/package/rework - https://github.com/reworkcss/rework
https://www.npmjs.com/package/htmlparser2 - https://github.com/fb55/htmlparser2
https://www.npmjs.com/package/flow - https://flowtype.org/
https://www.npmjs.com/package/jscodeshift - https://github.com/facebook/jscodeshift
https://www.npmjs.com/package/webidl2 - https://github.com/w3c/webidl2.js
Thanks for this great project …
=> add links for missing homepage urls

src/Toolbar.js, src/components/buttons/CategoryButton.js, src/components/buttons/ForkButton.js, src/components/buttons/ParserButton.js, src/components/buttons/SaveButton.js, src/components/buttons/TransformButton.js
Feel free to close/ignore this PR.  It's a very small refactor where I put all the toolbar buttons in their own folder.  There were already 3 buttons that existed: `CategoryButton`, `ParserButton`, `TransformButton`. I moved the 2 other `<div />` tags into their own components: `SaveButton` and `ForkButton`;
=> moving toolbar buttons to components/buttons

package.json, src/parsers/handlebars/glimmer.js, src/parsers/handlebars/transformers/glimmer/index.js, webpack.config.js, yarn.lock
The [glimmer](https://github.com/tildeio/glimmer) repo recently changed to publishing to an NPM org instead of several top-level packages, so this PR will replace `glimmer-syntax` with `@glimmer/syntax` and update it to the most current version.
/cc @fkling @mmun
=> Update "glimmer-syntax" to "@glimmer/syntax" v0.21.0

website/css/style.css, website/package.json, website/src/components/TransformOutput.js, website/src/parsers/handlebars/transformers/glimmer-compiler/codeExample.txt, website/src/parsers/handlebars/transformers/glimmer-compiler/index.js, website/webpack.config.js, website/yarn.lock
This PR also introduces the possibility to return a POJO from the transformer and have it displayed inside the `JSONEditor` component.
/cc @fkling @mmun
=> Add wireformat view for glimmer transform

website/package.json, website/yarn.lock
the yarn.lock has a few more changes than I initially expected. it looks like because flow-parser@0.37.0 required ast-types@0.18.15, yarn chose to install recast@0.10.43 which also uses that dependency. now, flow-parser@0.38.0 requires ast-types@0.18.18 and yarn thinks recast is better off using the older 0.10.33 that depends on ast-types@0.18.12 which it already has. there's probably no version of recast that depends on ast-types@0.18.18.
I ran this with yarn 0.19.1
=> Upgrade to flow-parser@0.38.0

website/package.json
Now that the folder structure has been re-organized, I tried:
```
cd website;
yarn start;
```
Which no longer served the website. This fixes the path to the `out` folder.
=> fix path to ../out directory

website/package.json, website/yarn.lock
flow-parser@0.40.0 fixes a small bug where sometimes line comments were parsed
as block comments. One example is code like
```
type T =
A | // Comment
B;
```
Please enter the commit message for your changes. Lines starting
=> Upgrade to flow-parser@0.40.0

website/package.json, website/yarn.lock
This version of flow-parser introduces object type spreads. They look like
```
type A = { x: string };
type B = { ...A };
```
=> Upgrade to flow-parser@0.42.0

website/css/style.css, website/package.json, website/src/app.js, website/src/components/Editor.js, website/src/components/JSCodeshiftEditor.js, website/src/components/Transformer.js, website/src/components/buttons/PrettierButton.js, website/src/containers/TransformerContainer.js, website/src/store/actions.js, website/src/store/reducers.js, website/src/store/selectors.js, website/yarn.lock
This allows prettier to run on the JSCodeshiftEditor. I'm not sure if 'blur' is the right time to run this honestly but at the very least I'm wondering if it's worth adding prettier to astexplorer.net somehow (maybe as a togglable option?). I definitely currently spend a lot of time just formatting code within the in-browser editor.
=> Add prettier to JSCodeshiftEditor

website/src/components/buttons/ParserButton.js, website/src/parsers/js/acorn-to-esprima.js, website/src/parsers/js/babel-eslint.js, website/src/parsers/js/transformers/eslint2/index.js, website/src/parsers/js/transformers/eslint3/index.js, website/src/parsers/js/utils/eslintUtils.js, website/src/parsers/utils/defaultParserInterface.js
The eslint setup in astexplorer is a bit chaotic. I'm not sure if it's worth investing a lot of time to clean this up in the light of  #197 (which I will hopefully finish some day 😛 ), so I just did some minimal changes:
- Switch the default parser for eslint2 and eslint3 to `babel-eslint`, because that's what `eslintUtils` uses.
- Enable `sourceType: 'module'` in `eslintUtils`.
- Make the `babel-eslint` parser actually refer to `babel-eslint` and not `acorn-to-esprima`.
- Since `acorn-to-esprima` is deprecated, hide in from the menu.
In order to really clean this up, `eslint1` would have to use an older version of `babel-eslint` that uses `acorn-to-esprima`, but I didn't want to spend more time with this.
@hzoo , does this look good?
cc @kentcdodds (follow up to #219 )
=> [eslint] Clean up eslint and babel-eslint

website/package.json, website/packages/eslint4/eslint4-package.js, website/packages/eslint4/index.js, website/packages/eslint4/package.json, website/src/parsers/js/transformers/eslint4/codeExample.txt, website/src/parsers/js/transformers/eslint4/index.js, website/src/parsers/js/utils/eslint4Utils.js
Question:
* Should we remove ESLint v1?
* Maybe v2 also?
=> New: ESLint v4

.eslintrc, website/src/parsers/scala/scalameta.js
Also make eslint fail if trailing commas are missing.
=> Add trailing commas to fix lint

.gitmodules, README.md, website/package.json, website/src/parsers/js/uglify.js, website/yarn.lock
uglify-es is now released from the "harmony" branch of
https://github.com/mishoo/UglifyJS2.git, so it should be equivalent.
See https://github.com/mishoo/UglifyJS2/tree/067d52b6bac67378cccbc8fdea2320676aafc47e
=> Use uglify-es instead of submodule

website/package.json, website/src/parsers/scala/scalameta.js, website/yarn.lock
2.0 introduces some breaking changes to the trees format.
=> [Scala] Update scalameta parser to 2.0

website/src/components/Editor.js, website/src/components/JSCodeshiftEditor.js, website/src/components/Toolbar.js, website/src/components/Transformer.js, website/src/components/buttons/KeyMapButton.js, website/src/containers/CodeEditorContainer.js, website/src/containers/ToolbarContainer.js, website/src/containers/TransformerContainer.js, website/src/store/actions.js, website/src/store/reducers.js, website/src/store/selectors.js
First, thanks so much for this project! It's made my journey diving into the world of ASTs so much easier.
This pull request adds the ability to customize the key mapping for the `Editor` and `JSCodeShiftEditor` CodeMirror instances with mappings for `emacs`, `sublime`, and (last but not least) `vim`.
Things to note:
---
- I went ahead and just stuck another button on the top row; this works but I'd be open to exploring a more meta "options page" if that's a good fit
- Because `Editor` and `JSCodeShiftEditor` share the same class but have different containers I had to duplicate some prop passing; let me know if there's a better way
- I'm not a fantastic designer, let me know if there's a preferred pattern for this UI
Things I tested:
---
Size
---
Also, including these additional mappings …
=> Add ability to customize key mappings to editor

website/src/components/visualization/Tree.js, website/src/components/visualization/tree/Element.js
The type keys seem redundant, added an option to hide them, making the AST more readable:
=> Add Hide type keys option

README.md, website/package.json, website/src/parsers/js/transformers/tslint/codeExample.txt, website/src/parsers/js/transformers/tslint/index.js, website/webpack.config.js
Hi.
This PR adds [TSLint](https://palantir.github.io/tslint/) (the Typescript Linter) as a transformer (issue #288).
Use it with the rule example that's in `tslint/codeExample.txt` to see it in action.
Right now though the rule itself can only be written in Javascript, not Typescript.
Ideally I'd like to support writing the rules in Typescript, as most TSLint users are accustomed to.
But I think this will require a change in how the `transformer.transform` is called.
Right now the original `transformCode` is turned into `es5Code` before the specific TSLint transformer is called, and by that point that conversion throws an error.
LMK if you need more info\changes.
Thanks.
=> Add TSLint support

website/src/parsers/js/babylon7.js, website/src/parsers/js/transformers/babel7/index.js, website/yarn.lock
This PR just adds the pipelineOperator plugin for babylon7.
It's disabled by default, but could be enabled from the settings.
=> Add pipelineOperator for Babylon7.

README.md, website/package.json, website/src/parsers/markdown/remark.js, website/yarn.lock
👋
This branch updates remark, removed an old option that’s no longer in use, and updates links to point to the new remark organisation.
[remark changelog »](https://github.com/remarkjs/remark/releases/tag/9.0.0)
=> remark@9.0.0

website/src/parsers/js/espree.js
I'm writing an ESLint rule that deals with async/await. Currently, ecmaVersions 8 and 9 are not included in the Espree parser settings on astexplorer.net. This PR updates the Espree settings to include ecmaVersions 8 and 9, which are [supported by Espree 3.5.2](https://github.com/eslint/espree/tree/v3.5.2#usage) (this version is listed as the resolved dependency in the website's `yarn.lock` file).
https://github.com/fkling/astexplorer/blob/262c60f650e178c711ddba9b18c4be9f2f510c41/website/yarn.lock#L2695-L2700
async/await parsing error
async/await parsed successfully
=> Add ecmaVersions 8 and 9 to Espree parser settings

website/package.json, website/src/parsers/js/flow.js, website/yarn.lock
* Added support for nullish coalescing `??`.
* Simplified object type parsing. Dangling `+` or `static` inside an object type (e.g. `{+}`) are now disallowed.
* Added support for a `proto` modifier in declare class, to specify that the property is a prototype property instead of a class one.
* Internal slot properties in object types (e.g. `[[new]]`).
* Explicit type arguments in new and call expressions, e.g., `f<T>(x)`.
* Allow reserved words as optional chain property names.
* The AST has been updated to use snake_case for record fields rather than camelCase. Some field names have also been updated.
* Support has been added for the [Numeric Separators proposal](https://github.com/tc39/proposal-numeric-separator), currently Stage 3.
* The AST representation for [Optional …
=> flow v0.72.0

website/package.json, website/src/parsers/wat/codeExample.txt, website/src/parsers/wat/index.js, website/src/parsers/wat/wat-parser.js, website/webpack.config.js, website/yarn.lock
A bit of background, WebAssembly is a new language / runtime for the web. This pull request adds support for the WebAssembly Text Format (WAT), as described by the spec:
https://webassembly.github.io/spec/core/index.html
The parser itself is from the [webassemblyjs](https://github.com/xtuc/webassemblyjs) project, which I'm actively involved in.
A couple of issues:
- codemirror doesn't support syntax highlighting for WAT yet.
- from integrating with this tool, I've noticed that our nodes don't all provide location information. Something for us to improve on!
=> feat: add wat parser

website/packages/babylon7/package.json, website/src/parsers/js/recast.js, website/yarn.lock
This allows parsing TypeScript sources when the babylon@7 'typescript' plugin is used:
Once a [new version of jscodeshift is released to support TypeScript](https://github.com/facebook/jscodeshift/issues/180#issuecomment-364800400), this will be useful as a tool to author TypeScript transforms.
=> Add babylon7 as an available parser for recast

website/src/parsers/js/acorn.js
acorn now support ecmaVersion 9 and 10.
And it need at least 9 to support for await of syntax.
=> Add ecmaVersion option 9, 10 for acron

website/package.json, website/yarn.lock
This brings the GraphQL parser up to date with the June 2018 version of
the GraphQL specification [[Ref 1]].  Amongst the features supported within
this newer version are string literal descriptions [[Ref 2]], so this
resolves fkling/astexplorer#312.
[Ref 1]: https://facebook.github.io/graphql/June2018/
[Ref 2]: https://facebook.github.io/graphql/June2018/#sec-Descriptions
Fixes: fkling/astexplorer#312
=> Update `graphql` to latest stable release 0.13.2.

website/src/parsers/js/transformers/babel-plugin-macros/index.js
The "babel-plugin-macros" transform is currently erroring with: 
`The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.`
This should fix that.
=> [babel-plugin-macros] Add "decoratorsBeforeExport" option when specifying decorators plugin

website/package.json, website/src/parsers/js/transformers/babel-plugin-macros/index.js, website/yarn.lock
Fixes #380
Importing a module with the `babel-plugin-macros` transform threw an error because it uses the `fs` module (which is empty in ASTExplorer's build). `v.2.5.0` of `babel-plugin-macros` adds a `resolvePath` option that lets ASTExplorer bypass the `fs` call.
=> Use custom resolvePath in babel-plugin-macros

website/src/parsers/js/babylon.js, website/src/parsers/js/babylon6.js, website/src/parsers/js/babylon7.js, website/src/parsers/js/flow.js
This makes it possible to see the individual tokens generated by the Flow and Babel parsers. Highlighting even works out of the box since tokens have the same location schema as nodes.
A similar capability can probably be added to some of the other parsers - I'm just less familiar with their APIs and I've needed these two in particular.
=> Add tokens option for Flow and Babylon parsers

README.md, website/package.json, website/src/parsers/solididy/codeExample.txt, website/src/parsers/solididy/index.js, website/src/parsers/solididy/solidity-parser-antlr.js, website/yarn.lock
Add [solidity-parser-antlr](https://github.com/federicobond/solidity-parser-antlr) parser for [Solidity](https://solidity.readthedocs.io/en/v0.5.3/index.html).
Pull request for issue #374
=> Add Solidity parser solidity-parser-antlr

website/src/parsers/html/angular.js
Output event not parsed - `Unexpected node BoundEvent`
```html
<!DOCTYPE html>
<html>
<body>
<h1>My First Heading {{param.name}} </h1>
<p>My first paragraph.</p>
<button (click)="s()"></button>
</body>
</html>
```
after change:
=> Add support BoundEvent for angular template parser

website/src/parsers/js/typescript-eslint-parser.js
Fixes https://github.com/fkling/astexplorer/issues/379
The default values are of course debatable...
=> Add ecmaVersion and sourceType options to typescript-eslint-parser

website/src/parsers/css/csstree.js, website/src/parsers/glsl/glsl-parser.js, website/src/parsers/graphviz/redot.js, website/src/parsers/icu/intl-messageformat-parser.js, website/src/parsers/json/json-to-ast.js, website/src/parsers/markdown/remark.js, website/src/parsers/mdx/mdxhast.js, website/src/parsers/regexp/regexp-tree.js, website/src/parsers/scala/scalameta.js, website/src/parsers/sql/sqlite-parser.js, website/src/parsers/wat/wat-parser.js, website/src/parsers/yaml/yaml.js
All of these have exactly same implementations as the base one and only make it harder to find real custom overrides.
=> Remove unnecessary getNodeName overrides

website/src/parsers/html/vue.js
It looks like a copy-paste from htmlparser2, despite the Vue parser not having the extra `name` property.
=> Fix Vue implementation of getNodeName

website/src/parsers/html/angular.js
This is more consistent with other HTML parser, and tends to be more useful than just `Element` on each element node.
=> Show tag names on elements in Angular parser

website/src/components/visualization/tree/Element.js, website/src/parsers/css/cssom.js, website/src/parsers/graphql/graphql-js.js, website/src/parsers/html/angular.js, website/src/parsers/html/htmlparser2.js, website/src/parsers/html/parse5.js, website/src/parsers/html/vue.js, website/src/parsers/js/typescript.js, website/src/parsers/js/uglify.js, website/src/parsers/php/php-parser.js, website/src/parsers/utils/defaultParserInterface.js, website/src/parsers/webidl/webidl2.js, website/src/parsers/yaml/yaml-ast-parser.js
Initially the checkbox was implemented only with a hardcoded `type` key in mind despite various parsers using different properties for the `getNodeName`, which resulted in a checkbox not having any effect for these parsers.
This adds a new property `typeKeys: Set<string>` that can be used on parsers with custom `getNodeName` to override set of keys that should be hidden when the checkbox is enabled.
=> Properly hide type keys in different parsers

README.md, website/package.json, website/src/parsers/handlebars/ember-template-recast.js, website/yarn.lock
This adds  _ember-template-recast_ to the list of available handlebars template parsers. Ember Template Recast allows to preserve e.g. the formatting of the handlebars templates it transforms. This PR only adds the parser functionality of the library for now for inspection of ASTs in the explorer. I can take a look into adding a transform based on Ember Template Recast in a second PR.
See also https://github.com/ember-template-lint/ember-template-recast
=> Add support for "Ember Template Recast" parser

website/src/components/ASTOutput.js, website/src/components/visualization/JSON.js, website/src/components/visualization/Tree.js, website/src/components/visualization/css/tree.css, website/src/components/visualization/tree/Element.js, website/src/core/ParseResult.js, website/src/core/TreeAdapter.js, website/src/parsers/js/utils/defaultESTreeParserInterface.js, website/src/store/parserMiddleware.js
Note: I'm going to merge this immediately because it fixes #398, but this can serve as a place to discuss the overall new approach.
---
A design flaw of the current implementation is that a parser adapter/wrapper (the files in `src/parser/`) serves multiple purposes, one of them being to encapsulate how astexplorer can interact with the resulting AST (e.g. get the node of name, it's children, etc). This tight coupling makes it difficult to improve the logic around parser.
As a first step this commit introduces a "tree adapter" which encapsulates all the AST interfacing logic. Eventually, parser will return a tree adapter configuration from their parse method. The interface / configuration options are subject to change as the existing parser are migrated over. For now the parser middleware …
=> Introducing TreeAdapter

website/src/parsers/js/flow.js, website/yarn.lock
Update to Flow 0.103. Add option (default off) to parse experimental enums. 
Tested through `yarn run build && yarn run start`, checking out website locally
=> flow 0.103

website/package.json, website/src/parsers/lucene/codeExample.txt, website/src/parsers/lucene/index.js, website/src/parsers/lucene/lucene.js, website/yarn.lock
The [lucene query syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html)
is widely spread across tools and databases, e.g. Elasticsearch and solr..
It is also commonly used in products to enable rich search capabilities, e.g.
Instana, Slack, LogDNA and more.
Add a new parser to the website to parse lucene to AST and to provide
node highlighting support.
Fixes https://github.com/bripkens/lucene/issues/25
=> Add lucene query syntax AST parser

website/css/style.css
This PR fixes the overflowing toolbar menu on smaller screens.
Before: 
After:
=> Fix overflowing toolbar menu

website/src/parsers/js/recast.js
This adds typescript support for recast.
This follows the example given in the recast docs
```javascript
const tsAst = recast.parse(source, {
parser: require("recast/parsers/typescript")
});
```
https://github.com/benjamn/recast#using-a-different-parser
=> Issue #438 - Add typescript as a parser for recast

website/src/parsers/js/transformers/babel7/index.js
Using retain lines causes some really ugly printing when the transform replaces nodes. The [https://astexplorer.net/#/gist/cfe3629169c8b47714064648e372c265/cc5b0e00d9dee45a53fc55f280be0cb36d53028b](example) I have on hand has the `you` variable adding several newlines to keep the same sourceline location. The `_template` function which is injected is also really ugly to look at.
Compare that with the output when `retainLines` is set to false (look for the commented out `pre()` block). Babel uses a rudimentary pretty-printer by default.
=> Disable retainLines in babel7 output

website/package.json, website/yarn.lock
* [#159](https://github.com/ember-template-lint/ember-template-recast/pull/159) Ensure templates with whitespace control are codemoded properly. ([@rwjblue](https://github.com/rwjblue))
* [#158](https://github.com/ember-template-lint/ember-template-recast/pull/158) Fix transform documentation ([@dcyriller](https://github.com/dcyriller))
* [#157](https://github.com/ember-template-lint/ember-template-recast/pull/157) Fix method name in README ([@dcyriller](https://github.com/dcyriller))
- Cyrille David ([@dcyriller](https://github.com/dcyriller))
- Robert Jackson ([@rwjblue](https://github.com/rwjblue))
- [@dependabot-preview[bot]](https://github.com/apps/dependabot-preview)
* [#154](https://github.com/ember-template-lint/ember-template-recast/pull/154) fix: Make it possible to annotate …
=> Update ember-template-recast to v3.2.8.

README.md, website/package.json, website/src/parsers/regexp/regjsparser.js, website/webpack.config.js
In this PR we add regjsparser support to astexplorer.
Background: regjsparser is used by a popular library `regexpu-core`, which transpiles unicode related regular expressions to ES5. `@babel/preset-env` replies on `regexpu-core` for unicode regex features.
When we are investigating babel issues about unsupported regex, I realize it would be convenient to browse the ast generated by regjsparser, isolate the problem and to see if it is on the parser side or the transformer side.
=> feature: add regjsparser

website/src/components/visualization/tree/Element.js
This allows methods on nodes to be called; specifically, the majority of methods on TypeScript Nodes can now be called.
There is a better way to implement this somewhere, but this was the simplest low-key way I could hack together given that my IDE just can't handle this repo :joy:
This includes `getSourceFile`, which now runs perfectly instead of locking the whole tab up.
=> Bind function values to node so that they have the correct `this` when called

website/package.json, website/yarn.lock
Primary changes:
* Fix a number of bugs
* Drop support for Node 8
---
<details>
<summary>Changes from 3.2.8 -> 4.1.1</summary>
* [#223](https://github.com/ember-template-lint/ember-template-recast/pull/223) Ensure updating self-closing ElementNode preserves trailing whitespace. ([@rwjblue](https://github.com/rwjblue))
- Robert Jackson ([@rwjblue](https://github.com/rwjblue))
* [#219](https://github.com/ember-template-lint/ember-template-recast/pull/219) Expose metadata (isValueless / quoteType) on AttrNode's ([@rwjblue](https://github.com/rwjblue))
- Robert Jackson ([@rwjblue](https://github.com/rwjblue))
* [#216](https://github.com/ember-template-lint/ember-template-recast/pull/216) Fix quoting for `TextNode`'s originally used as an `AttrNode` value. …
=> Update ember-template-recast to 4.1.1.

website/src/parsers/reason/refmt.js
Hi!
Thanks for AST explorer. It's an invaluable tool to develop syntax extensions for OCaml.
This PR adds `loc` to `locKeys` in refmt, which was previously missing. It corresponds to the `'a loc` type of the OCaml AST, which associate a piece of data with a location.
For example, on the OCaml example, selecting "Printf" highlights a node of type `Longident.t Asttypes.loc`. These nodes have a `txt` field and a `loc` field.
<details>
<summary>Screenshots</summary>
</details>
Thanks!
=> refmt: add 'loc' to locKeys

website/src/parsers/js/acorn.js
Old url 404ed, new one works :)
=> Update acorn option descriptions url

website/src/parsers/js/babylon7.js
I would like to propose enabling `nullishCoalescingOperator` for babylon7 by default, given that it is enabled for `babel-plugin-macros`, `flow` parser. It also works in typescript parser out of the box and it is now works in the [latest chrome and firefox versions](https://caniuse.com/#feat=mdn-javascript_operators_nullish_coalescing). I think it is a good idea for this plugin to be enabled by default.
=> enable nullishCoalescingOperator for babylon7 by default

website/package.json, website/src/parsers/solididy/solidity-parser-diligence.js, website/yarn.lock
[solidity-parser-diligence](https://github.com/ConsenSys/solidity-parser-antlr) is a fork of solidity-parser-antlr that supports solidity 0.6.x.
=> Add solidity-parser-diligence

website/src/parsers/js/babylon7.js
This PR refurbishes babel 7.9 support:
- Added more available proposals and language extensions
- Added more parser options
- Removed stage-4 proposals which are always enabled in `@babel/parser`
- Added stage-3 proposals to default options
=> refurbish babel 7.9 support

README.md, website/package.json, website/src/parsers/regexp/regexpp.js, website/webpack.config.js, website/yarn.lock
I added support for the [regexpp](https://github.com/mysticatea/regexpp) parser.
Or, I _think_ I did. The build (with and without my changes) fails on my system and I have no idea why.
<details>
<summary>Log</summary>
```
C:\Users\micha\Git\astexplorer\website>yarn run build
yarn run v1.22.4
$ rimraf ../out/* && cross-env NODE_ENV=production webpack --mode=production
build [====                ] 20%[BABEL] Note: The code generator has deoptimised the styling of C:\Users\micha\Git\astexplorer\website\node_modules\prettier\standalone.js as it exceeds the max of 500KB.
build [==============      ] 69%[BABEL] Note: The code generator has deoptimised the styling of C:\Users\micha\Git\astexplorer\website\node_modules\svelte\compiler.js as it exceeds the max of 500KB.
Build completed in 115.246s …
```
=> Added Regexpp parser

website/css/style.css, website/src/app.js, website/src/components/SettingsDrawer.js, website/src/containers/SettingsDrawerContainer.js, website/src/store/actions.js, website/src/store/reducers.js, website/src/store/selectors.js
Part of https://github.com/fkling/astexplorer/issues/468
A really basic version of a settings drawer that opens and closes. Will build on this in subsequent PRs 😄 
I've removed it from `app.js` so it doesn't actually render for users, but if you want to try it out you can undo [this commit](https://github.com/fkling/astexplorer/pull/489/commits/80c462f2ef30e24dbac8eb2a706448c151a8fd8b). Will squash when I merge, just wanted to show how it would be added to app.js in future.
=> Add basic settings drawer

website/src/parsers/js/babylon7.js
Supports selecting whichever pipeline proposal.
I'm gonna add "hack" (hopefully after adding it to Babel) later.
Before this commit:
After this commit:
=> JavaScript, Babylon7, support selecting pipeline proposal

.gitignore, website/.npmrc
I assumed `package-lock.json` wasn't meant to be checked in, seeing as it wasn't already in the repo.
Disabling it at a repo level so it doesn't get generated in the first place.
=> chore: disable package-lock

website/package.json, website/yarn.lock
Went through https://github.com/typescript-eslint/typescript-eslint/blob/v3.6.0/CHANGELOG.md and didn't find new parser options added.
=> feat: Bump `@typescript-eslint/parser` to 3.6.0

website/package.json, website/yarn.lock
Went through https://github.com/typescript-eslint/typescript-eslint/blob/v4.1.0/CHANGELOG.md and didn't find new parser options added.
=> feat: Bump `@typescript-eslint/parser` to 4.1.0

website/package.json, website/src/parsers/san/codeExample.txt, website/src/parsers/san/index.js, website/src/parsers/san/san-template-parser.js, website/yarn.lock
I'm working on san related projects and find it extreme useful to have a AST viewer for it. And then  I find astexplorer as a start point. After using my local astexplorer for a while and made [some changes on san](https://github.com/baidu/san/pull/527/files) to work well with astexplorer, I find it's potentially also useful for many people working on or using san.
San is an MVVM component-based framework, basically similiar to Vue but, fosusing on compatibility and performance. Here's a template parser using its own `parseTemplate()`. See this page for more about San: https://baidu.github.io/san/en/index.html
The AST tree viewer for San template is useful for both development for [san][san], [san-ssr][san-ssr] and build tools like [san-anode-utils][san-anode-utils] and …
=> Add a category and the corresponding template parser for San

website/package.json, website/yarn.lock
This PR pulls in the newest version of the Rust parser:
- A few syntax tree changes in the underlying Rust library between 0.15 and 1.0: https://github.com/dtolnay/syn/releases/tag/1.0.0#user-content-breaking-changes
- The corresponding PR to the npm package: https://github.com/RReverser/astexplorer-syn/pull/1
---
=> Update Rust parser to syn 1.0

website/src/core/TreeAdapter.js
This allows holes to be visible in code like:
```mjs
let foo = [1,,3];
let [a,,c] = foo;
```
This also means humans reading arrays can see the correct index while viewing.
=> Fix avoid hiding empty array elements

website/package.json, website/yarn.lock
http-server does not send the proper MIME header for .wasm files, which prevents
development of WebAssembly-based parsers like swc. serve supports this use case,
and is edited by Vercel (previously Zeit) with 6.5k stars on GitHub.
=> Switch to vercel/serve for yarn start

website/src/parsers/js/transformers/typescript/index.js
Changes the typescript transformer to use the public api instead of internal typescript API calls.
Also:
- added a type check to give some sane feedback if the user messes up.
- added some comments to document what each piece of code does.
=> fix: remove internal typescript api calls in the typescript transformer

website/src/parsers/js/shift.js, website/src/parsers/utils/defaultParserInterface.js
I don't love the global state approach to storing side tables, but it seems to be the preferred approach (I copied it from the [typescript parser](https://github.com/fkling/astexplorer/blob/a565b32ecce73118ad82bbf5997367b19bd02f94/website/src/parsers/js/typescript.js#L66)).
=> provide location information for shift-parser

README.md, website/package.json, website/src/components/ASTOutput.js, website/src/parsers/js/hermes.js, website/src/parsers/js/hermes/HermesWorkerClient.js, website/src/parsers/js/hermes/hermes-worker.js, website/yarn.lock
(EDIT: Updated June 2021.)
Adds the [Hermes engine](https://github.com/facebook/hermes)'s parser into AST Explorer. Try it at [astexplorer-hermes.now.sh](https://astexplorer-hermes.now.sh).
Implementation notes:
1. This uses the official [hermes-parser](https://www.npmjs.com/package/hermes-parser) npm package and supports all of its options (except `sourceFilename`).
2. We wrap the parser in a Web Worker, because some browsers will refuse to synchronously load a WebAssembly module on the main thread when it's as big as the one `hermes-parser` uses. As a side benefit, this is also nice for UI perf.
3. There is some subtlety to how errors are reported because of the worker architecture - sending `Error` instances over `postMessage` behaves differently across browsers so I've ditched that. …
=> Add Hermes parser for JavaScript

website/src/parsers/js/hermes.js
Quick follow up from #504 fixing location handling with the Hermes parser. Adds a `nodeToRange` method supporting the two different AST formats generated by `hermes-parser`, as well as matching `locationProps`.
Test plan:
1. Ensure that "Hide location data" works for both `babel: false` and `babel: true`.
2. Ensure that hovering a node highlights the corresponding code for both `babel: false` and `babel: true`.
=> Fix node range handling in Hermes parser adapter

website/src/parsers/js/transformers/jscodeshift/codeExample.txt, website/src/parsers/js/transformers/jscodeshift/index.js, website/src/store/reducers.js
Looking for a little discussion on approach! I use AST explorer only every so often and most recently I found myself stumbling a bit again when I tried to write a jscodeshift transform, and was only met with the error below:
Here's an attempt to demystify some of this by adding the `module.exports.parser` directly to the code example (with a cute little formatter to automatically inject the "tsx" transformer)
Here's a gif of the flow:
https://user-images.githubusercontent.com/3484848/120608590-34d2a500-c406-11eb-86da-6c49c89bc298.mp4
----
This adds two new configuration options for transformers:
- compatibleParserIDs
- formatCodeExample
compatibleParserIDs is used in SELECT_TRANSFORMER as an alternative to
always resetting the parser when changing the transformer or turning it
on. If we …
=> feat: [transformers] add example formatting + compatible parsers

website/package.json, website/yarn.lock
This PR upgrades the svelte transformer from version 3.20.1 to 3.44.3.
This allows for newer Svelte language features to be parseable.
For example, the [`$$slots` object](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3250) was added in Svelte version 3.25. With v3.20, we encounter an "illegal variable name" error:
The syntax is valid when using the latest version:
=> Upgrade svelte transformer to version 3.44.3

website/src/parsers/html/angular.js
This PR fixes the following issues:
1. When using the Angular HTML parser, the site crashes (stuck in an infinite loop) with the following template:
```html
<div *ngFor="let hero of heroes; let i=index; let odd=odd; trackBy: trackById">
({{i}}) {{hero.name}}
</div>
```
This is caused by the `fixSpan` method, which isn't handling bound attributes from structural directives and has a `while` loop with a stop condition that doesn't meet in this case.
2. The attribute span indexes are incorrect since it returns the first `=` index after the attribute, for example:
```html
<div *ngFor="let hero of heroes; let i=index; let odd=odd; trackBy: trackById" [class.odd]="odd">
({{i}}) {{hero.name}}
</div>
```
* The `ngForOf` bound attribute should have the following span: `{start: 22, end: 28}` but it …
=> fix: site stuck in infinite loop

website/package.json, website/yarn.lock
Since the v4, TS added new syntaxes (specially in this new v4.7.0), so this PR aims to update both TS and @typescript-eslint/parser to be able to support those new syntaxes (and to be up to date with the latest version of TS in general):
- `typeof y.z<w>`
- `withGeneric<T>`
- covariant and contravariant `in` and `out`
See https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/ & https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.27.0.
Before | After
-|-
Before | After
-|-
=> [Updates] typescript v4.7.0 & @typescript-eslint/parser v5.27.0

website/src/parsers/js/transformers/eslint8/codeExample.txt
Fixes the current error that appears on the site when you delete the `${i}` from the example:
> Fixable rules must set the `meta.fixable` property to "code" or "whitespace".
> Occurred while linting <input>:18
> Rule: "astExplorerRule"
With this change it will be easier to modify the example rule to make fixes and suggestions.
=> Improve ESLint v8 example rule 

website/src/parsers/js/babylon7.js, website/yarn.lock
In this PR we update `@babel/parser` to 7.19 and support more plugin options.
=> Babel 7.19

website/package.json, website/yarn.lock
Currently, the Svelte compiler is unable to recognize `svelte:element` tags or `@const` tags in `#if` blocks. This PR upgrades svelte to the latest minor version.
In the AST Explorer, the Svelte compiler is unable to parse the following code. It works in the [Svelte REPL](https://svelte.dev/repl/dd9b63a367cc46139ab770341d45f2d5?version=3.49.0) when using the latest minor version.
```svelte
{#if true}
{@const a = 44}
{a}
{/if}
<svelte:element this="h6">
h6 tag
</svelte:element>
```
=> Upgrade svelte to 3.52

README.md, website/src/parsers/svelte/codeExample.txt, website/src/parsers/svelte/index.js, website/src/parsers/svelte/svelte-parser.js
Currently, Svelte is a parser under the HTML category. Although Svelte markup is a superset of HTML, Svelte can be considered its own language[^1].
This PR adds Svelte as its own top-level category, which also makes it easier to locate.
[^1]: [what-is-svelte.md](https://gist.github.com/Rich-Harris/0f910048478c2a6505d1c32185b61934)
=> Add Svelte as a top-level category

website/package.json, website/src/parsers/sql/sql-parser-cst.js, website/yarn.lock
Here's a pull request to support new parser for SQL.
As it supports parsing multiple SQL dialects (though for now only two) I've included a config option to switch between the dialects, plus a few more settings.
PS. This is an awesome project. I've been happily using this for years. Big thanks for creating and maintaining it 👍
=> Add new SQL parser: sql-parser-cst

website/package.json, website/yarn.lock
I tested it locally, and I confirmed it works as I expected. (4.7.0 contains a bunch of bug fixes from the previous version).
=> Bump scalameta-parsers to 4.7.0

README.md, website/src/parsers/lua/luaparse.js
The old `luaparse` website url is now 404.
Update to https://fstirlitz.github.io/luaparse/
=> Update luaparse website url

website/package.json, website/src/parsers/js/hermes/hermes-worker.js, website/yarn.lock
I've updated the hermes-parser dependency to 0.18.0.
Changelog can be found here: https://github.com/facebook/hermes/blob/main/tools/hermes-parser/js/CHANGELOG.md
I've tested this locally and verified there are no errors and the latest features of hermes-parser are working as expected.
=> chore(deps): update hermes-parser to 0.18.0

website/package.json, website/yarn.lock
Pull request to fix the issue: CodeMirror editor displays error on JavaScript class private fields
Fixes #702
Updated codemirror version to the lastest _^5_ in _package.json_ and _yarn.lock_.
=> feat: Update codemirror version
