fkling/astexplorer

package.json

npm install broken

---

src/transformExample.txt

Also used const instead of var now that we sort es6 in the transforms :)

Add template helpers to transform example

---

css/style.css

Mostly so you can copy+paste node types. cc: @fkling

Allow user selection of strings in tree

---

src/utils/stringify.js

Fix display of null values

---

css/style.css

Hello, I use and enjoy astexplorer alot lately but there are two little styling things that distract me so I tried to fix them. I hope it's OK with you.
- Menu item does not change its width when children are shown when mouseover
- Submenu is wide at least as it's parent item
Best regards,
J

Little style improvements in main menu

---

src/TransformOutput.js
src/app.js
src/parsers/css/transformers/postcss/codeExample.txt
src/parsers/css/transformers/postcss/index.js
src/parsers/utils/compileModule.js

Depends on #62.
@fkling I know you're trying to merge, so sent as separate PR for this. Sooorrry :)

Add PostCSS transform mode

---

src/ASTOutput.js
src/Editor.js
src/JSONEditor.js
src/LocalStorage.js
src/PasteDropTarget.js
src/Snippet.js
src/SnippetRevision.js
src/SplitPane.js
src/TransformOutput.js
src/app.js
src/components/ast/CompactArrayView.js
src/components/ast/Element.js
src/components/ast/RecursiveTreeElement.js
src/components/visualization/Tree.js
src/parsers/css/postcss.js
src/parsers/html/htmlparser2.js
src/parsers/html/parse5.js
src/parsers/js/acorn.js
src/parsers/js/babylon.js
src/parsers/js/babylon6.js
src/parsers/js/codeExample.txt
src/parsers/js/espree.js
src/parsers/js/esprima.js
src/parsers/js/recast.js
src/parsers/js/shift.js
src/parsers/js/traceur.js
src/parsers/js/transformers/jscodeshift/codeExample.txt
src/parsers/js/typescript.js

Used a bunch of transformers (public and handwritten) to use new ES6/ES7 constructions where it makes sense.
I was mostly doing this just to finally try jscodeshift on a real project and play with custom transformations, so if you don't want to accept such a big changes, I'm totally fine with it.

ES6ify code a bit

---

package.json
src/parsers/html/parse5.js

This one currently lives on top of #75, but if it will be rejected, I can easily rebase and fix on top of ES5 code.

Update parse 5

---

src/PasteDropTarget.js
src/Snippet.js
webpack.config.js

As mentioned, I think it's relatively rarely used, so can be safely split & loaded only when JSON is dropped.

 Shave off another second by loading Escodegen with deps on demand.

---

package.json

see https://github.com/fkling/astexplorer/issues/89

serve correct directory

---

package.json
src/parsers/js/flow.js

Includes various new syntax and early-stage feature options

Update Flow parser to v0.21

---

css/style.css

Currently the menu buttons uses the browser default font. Fix that.

Fix style of menu button

---

src/parsers/js/transformers/babel/index.js
src/parsers/js/transformers/babel6/index.js

Ref https://github.com/fkling/astexplorer/issues/44
cc @RReverser

Only transform the user's plugin

---

src/parsers/css/transformers/postcss/codeExample.txt

To match preferred code style in transform plugins (guess this is referring to https://github.com/postcss/postcss-plugin-boilerplate/commit/4d05aabcacd5648bb115108cfff1f4831fb190f2)
for #147

Update PostCSS transform example

---

package.json

Pretty self-explanatory :smile:

Allow building on Windows using cross-env

---

src/parsers/js/babylon6.js

in https://github.com/babel/babylon/releases/tag/v6.12.0

add dynamicImport plugin

---

package.json
src/TransformOutput.js
src/parsers/js/babylon6.js
src/parsers/js/transformers/babel6/index.js
src/parsers/utils/transformJSCode.js
yarn.lock

Fixes https://github.com/fkling/astexplorer/issues/163

Allow stage-0 syntax in transform plugins

---

src/components/ast/CompactArrayView.js
src/components/ast/CompactObjectView.js
src/components/visualization/JSON.js

I made `JSON.propTypes.ast` match `Tree.propTypes.ast`, see:
https://github.com/fkling/astexplorer/blob/b5c36c1689e3638bc6dddf61f56d0e3f4770adaa/src/components/visualization/Tree.js#L86-L89
I also confirmed my local build works.

fixing eslint errors

---

README.md

Here's what the changes will look like on Github: https://github.com/skratchdot/astexplorer/blob/yarn/README.md

more yarn instructions. see #156

---

website/package.json
website/yarn.lock

Significant updates:
https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha14
https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha15

Bump csstree to 1.0.0-alpha15

---

website/package.json
website/packages/eslint3/eslint3-package.js
website/packages/eslint3/index.js
website/packages/eslint3/package.json
website/src/parsers/js/transformers/eslint3/codeExample.txt
website/src/parsers/js/transformers/eslint3/index.js

New: Add ESLint v3

---

website/package.json
website/src/parsers/icu/intl-messageformat-parser.js
website/yarn.lock

thanks to @ericf for the fast response and release of https://github.com/yahoo/intl-messageformat-parser/pull/17!
/cc @fkling

icu: Add location support

---

website/src/parsers/js/babylon6.js

Add estree option to babylon 6

---

website/src/parsers/js/utils/eslintUtils.js

Ref #117 
I haven't actually tested this out but it seems like this would be the change to make until we add a UI to configure the transform...

improve defaults for eslint transform

---

website/packages/babel7/package.json
website/packages/babylon7/package.json
website/src/parsers/js/babylon7.js
website/src/parsers/js/transformers/babel7/index.js
website/src/parsers/utils/transformJSCode.js

update to alpha.12

---

website/src/parsers/js/babylon7.js

This was readded in babel/babylon#363

Add ranges options to babylon 7

---

website/package.json

More info - https://github.com/fkling/astexplorer/issues/235 and https://github.com/yarnpkg/yarn/issues/3560

Pinned csstree version (closes #235)

---

.travis.yml

See https://docs.travis-ci.com/user/migrating-from-legacy/ and
https://github.com/fkling/astexplorer/pull/243#issuecomment-309793533

Use container-based infrastructure on Travis

---

website/package.json
website/yarn.lock

A Greepkeeper integration would be amaze!

Upgrade to Typescript 2.4

---

website/src/parsers/js/babylon7.js

Resolves https://github.com/fkling/astexplorer/issues/267

Add TypeScript option to Babylon 7

---

website/package.json
website/yarn.lock

$ cd website
$ yarn upgrade flow-parser@^0.63.0

flow v0.63.1

---

README.md
website/package.json
website/src/parsers/graphviz/codeExample.txt
website/src/parsers/graphviz/index.js
website/src/parsers/graphviz/redot.js
website/yarn.lock

This adds a Graphviz AST using [redot](https://github.com/redotjs/redot)

Add Graphviz support with the redot parser

---

website/package.json
website/src/parsers/js/transformers/babel-macros/codeExample.txt
website/src/parsers/js/transformers/babel-macros/index.js
website/webpack.config.js
website/yarn.lock

I added a new transformer to develop and tinker with [babel-plugin-macros](https://github.com/kentcdodds/babel-plugin-macros) right on astexplorer.
You can give it a try [here](https://astexplorer.dev.weinberg.me/). (Choose Transform -> babel-macros)

Add babel-plugin-macros as a new transformer

---

website/src/parsers/js/utils/eslint4Utils.js

This makes it much nicer to test a new auto-fix plugin.
Fixes #123.

Allow auto-fixers with ESLint v4

---

website/src/parsers/js/transformers/eslint4/codeExample.txt

Re: https://github.com/fkling/astexplorer/pull/354#issuecomment-440574641

Add auto-fixing to eslint v4 example transformer

---

README.md
website/package.json
website/src/parsers/yaml/yaml.js
website/yarn.lock

Ref: https://github.com/eemeli/yaml

feat: add `yaml` parser

---

website/package.json
website/src/parsers/js/typescript-eslint-parser-legacy.js
website/yarn.lock

Ref: https://eslint.org/blog/2019/01/future-typescript-eslint#what-this-means-going-forward

feat: add @typescript-eslint/parser

---

website/src/parsers/handlebars/transformers/ember-template-recast/codeExample.txt
website/src/parsers/handlebars/transformers/ember-template-recast/index.js

see https://github.com/ember-template-lint/ember-template-recast :)
/cc @fkling @rwjblue @jessica-jordan

Add `ember-template-recast` transform support

---

README.md
website/package.json
website/src/parsers/html/svelte.js
website/webpack.config.js
website/yarn.lock

Fixes #404
1. Added Svelte link in README
2. Added svelte package
3. New parser for svelte under html
4. Added svelte node_modules in webpack config

[FEAT] Add Svelte parser for HTML

---

README.md
website/package.json
website/src/parsers/icu/intl-messageformat-parser.js
website/yarn.lock

New `intl-messageformat-parser` has a different AST

chore: upgrade intl-messageformat-parser

---

website/src/parsers/html/transformers/svelte/codeExample.txt
website/src/parsers/html/transformers/svelte/index.js

This will be really helpful to create codemod tooling for Svelte.
Hence I created a new transfomer for Svelte under HTML
Fixes #422

[FEAT] Add Svelte Transform under HTML

---

website/package.json
website/src/parsers/scala/scalameta.js
website/yarn.lock

Bump the Scalameta parser version and add a few more recent settings
I've tested this locally and I can confirm it works as expected.

Update scalameta-parsers to 4.2.1

---

website/package.json
website/yarn.lock

P. S. AST Explorer looks great. Thanks for including my package!

Update CSSOM to v0.4.1

---

website/package.json
website/yarn.lock

Fixes a bug with AST mutation.

Update ember-template-recast to 3.1.2.

---

README.md
website/package.json
website/src/parsers/html/posthtml.js
website/src/parsers/html/transformers/posthtml/codeExample.txt
website/src/parsers/html/transformers/posthtml/index.js
website/yarn.lock

I really wanted a way to run a transformer over HTML, so I added one. 
Let me know if there are any suggestions or changes you want me to make.

Added `posthtml` as parser and transformer

---

README.md
website/package.json
website/src/parsers/html/hyntax.js
website/yarn.lock

Hi! This is my html parser implementation, would be nice to have it here.

Add Hyntax Html Parser

---

website/package.json
website/src/parsers/yaml/yaml.js
website/yarn.lock

Untested, b/c my build won't finish locally :(

Update `yaml` parser to `^1.7.2` (from `^1.0.3`)

---

website/package.json
website/src/parsers/js/tenko.js
website/yarn.lock

Add Tenko to the hall of fame

---

website/package.json
website/src/parsers/go/codeExample.txt
website/src/parsers/go/go.js
website/src/parsers/go/index.js
website/webpack.config.js
website/yarn.lock

This PR will add the golang support into astexplorer.
Resolved #264

feat: Go support

---

website/package.json
website/yarn.lock

Tested by running:
```
cd website && yarn install && yarn run build-dev && yarn run start
```
And playing around locally.

Update flow-parser to 0.113

---

website/package.json
website/yarn.lock

Reverts fkling/astexplorer#467

Revert "Update flow-parser to 0.113"

---

website/css/style.css

Resolves https://github.com/fkling/astexplorer/issues/478

CSS: Apply `white-space: pre-wrap;` to values

---

website/package.json
website/src/parsers/thrift/codeExample.txt
website/src/parsers/thrift/index.js
website/src/parsers/thrift/thrift-parser.js
website/yarn.lock

Parser here: https://github.com/creditkarma/thrift-parser

Add thrift IDL

---

README.md

Added all Vue parsers to README
cc @sodatea

chore: Add Vue parsers to README

---

website/src/parsers/js/babylon7.js

Rename babylon7 to @babel/parser

---

website/package.json
website/src/parsers/python/codeExample.txt
website/src/parsers/python/index.js
website/src/parsers/python/python.js
website/yarn.lock

Close #482 
Uses https://github.com/codecombat/filbert

Close #482. Add Filbert for Python language support

---

website/package.json
website/src/parsers/js/eslint-parser.js
website/webpack.config.js
website/yarn.lock

Support @babel/eslint-parser@^7.11.5 as parser

Add new parser: @babel/eslint-parser

---

README.md
website/package.json
website/src/parsers/js/seafox.js

adding [seafox](https://github.com/KFlash/seafox)

add seafox js parser

---

website/package.json
website/src/parsers/vue/vue-compiler-dom.js
website/yarn.lock

Fix #526 and https://github.com/vuejs/vue-next/issues/1803
In compiler core we cannot have < in script section due to wrong parse options.

Use Vue compiler dom instead of compiler core

---

website/src/parsers/js/babylon7.js
website/yarn.lock

Updated `@babel/parser` to 7.12
Added new plugins supported in `@babel/parser`.

Babel 7.12

---

website/package.json
website/src/parsers/css/csstree.js
website/yarn.lock

- updated csstree to 1.0
- added csstree settings

Updated csstree to 1.0

---

website/package.json
website/src/parsers/html/angular-eslint.js
website/yarn.lock

Add new parser using https://github.com/angular-eslint/angular-eslint
I deployed it to my gh-pages. See https://quramy.github.io/astexplorer/

feat: Add angular-eslint HTML template parser

---

README.md
website/package.json
website/src/parsers/monkey/codeExample.txt
website/src/parsers/monkey/index.js
website/src/parsers/monkey/monkey.js
website/yarn.lock

Fix https://github.com/fkling/astexplorer/issues/554
I don't know the webpack magic, but it just works.

feat: add monkeylang

---

website/src/parsers/js/babylon7.js
website/yarn.lock

Updated `@babel/parser` to 7.13
Added new plugins supported in `@babel/parser`.

Babel 7.13

---

website/src/parsers/js/transformers/typescript/codeExample.txt
website/src/parsers/js/transformers/typescript/index.js

This PR will implement the typescript transformer API. The existing infrastructure made it extremly easy to implement.

feat: implement a typescript transformer

---

website/src/parsers/js/transformers/recast/codeExample.txt
website/src/parsers/js/transformers/recast/index.js

feat: add recast as transformer as well

---

website/src/parsers/js/babylon7.js
website/yarn.lock

Updated `@babel/parser` to 7.14
Added new plugins supported in `@babel/parser`.

Babel 7.14

---

website/package.json
website/src/parsers/scala/scalameta.js
website/yarn.lock

Add Scala 3 support

---

website/package.json
website/src/parsers/vue/vue-eslint-parser.js
website/yarn.lock

This PR upgrades vue-eslint-parser and adds new options.

Chore: upgrade vue-eslint-parser

---

website/package.json
website/yarn.lock

Looks like no code changes are needed 🤷 
cc @bradzacher

feat: update `@typescript-eslint/parser` to v5

---

website/package.json
website/yarn.lock

CSSTree 2.0 [release notes](https://github.com/csstree/csstree/releases/tag/v2.0.0)

Update to CSSTree 2.0

---

website/package.json
website/yarn.lock

Tested locally and still functioned as expected

Update to java-parser 2.0.1

---

README.md
website/package.json
website/yarn.lock

- Fixed a bunch of parse errors.
- https://github.com/pbkit/pbkit/issues/78
- https://github.com/pbkit/pbkit/issues/80
- https://github.com/pbkit/pbkit/issues/83
- https://github.com/pbkit/pbkit/issues/86
- https://github.com/pbkit/pbkit/issues/88
- https://github.com/pbkit/pbkit/issues/103
- https://github.com/pbkit/pbkit/issues/104
- https://github.com/pbkit/pbkit/issues/105
- Parsing comments more correctly.
- https://github.com/pbkit/pbkit/pull/166
- A simple level of error tolerance feature.
- https://github.com/pbkit/pbkit/commit/d334f37245cd879df9d8ddc2ceb0fb54229a169c
- <img width=340 src="https://user-images.githubusercontent.com/690661/152678006-54b14fcd-ffb3-4689-87f9-3bb6f4f33cc9.png">

Upgrade pbkit to v0.0.38

---

website/src/parsers/js/babylon7.js
website/yarn.lock

- Updated `@babel/*` to 7.18
- Added Babel 7.18 features

Babel 7.18

---

website/package.json
website/yarn.lock

Update [Angular ESLint](https://github.com/angular-eslint/angular-eslint) parser to latest version.

Update to latest version Angular ESLint

---

website/src/parsers/js/espree.js

updated as its docs: https://github.com/eslint/espree/tree/main#options

feat: update espree options

---

website/package.json
website/yarn.lock

Support Angular 17 - control flow (https://angular.io/guide/control_flow)
```html
<!DOCTYPE html>
<html>
<body>
@for (user of users; track user.id) {
<p>{{ user.name }}</p>
}
</body>
</html>
```

feat(angular): support angular v17

---

website/src/parsers/html/htmlparser2.js

Hide Location Data should hide this prop as well. (Note its use in nodeToRange)

[htmlparser2] add 'endIndex' to 'locationProps'
